[package]
name = "gom"
version = "0.1.4"
edition = "2021"
description = "A simple Rust global object manager"
license = "MIT"
repository = "https://github.com/Anglebase/GOM.git"

[dependencies]
constcat = "0.6.0"
lazy_static = "1.5.0"
